#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Nexacro MES 데이터 수집 파이프라인 (Playwright).

1. init 단계에서 hooking 스크립트 주입 (XHR/transaction/copyData 등)
2. 수동 로그인·조회 후 브라우저 컨텍스트에서 mesApiStore / nexacroDataStore / 그리드 매핑 수집
3. params.py 자동 생성 (NETWORK_JSON, RES_JSON, NEXACRO_DICT)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# 경로
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent
HOOK_DIR = ROOT / "hooking"


def _read_text(rel: Path) -> str:
    return rel.read_text(encoding="utf-8")


def _prepare_response_mapping_source() -> str:
    """
    response_mapping.js는 파일 끝에서 즉시 extractGridMappingsStructural()을 호출한다.
    add_init_script 시점에는 nexacro가 없어 실패하므로 마지막 호출만 제거하고
    이후 page.evaluate에서 호출할 수 있도록 전역에 노출한다.
    """
    src = _read_text(HOOK_DIR / "response_mapping.js")
    src = src.rstrip()
    src = re.sub(r"\nextractGridMappingsStructural\s*\(\s*\)\s*;\s*$", "", src)
    return src + "\nwindow.__mesExtractGridMappings = extractGridMappingsStructural;\n"


def _build_init_script_bundle(
    include_nexacro_response: bool = True,
) -> str:
    """
    단일 init 스크립트 문자열로 합친다 (등록 순서 = 실행 순서).

    nexacro_response.js를 network.js보다 먼저 두면, XHR send 체인에서
    응답 파서가 안쪽에 가깝게 동작한다 (둘 다 load 리스너만 추가하므로 필수는 아님).
    """
    parts: list[str] = []
    if include_nexacro_response:
        parts.append(_read_text(HOOK_DIR / "nexacro_response.js"))
    parts.append(_read_text(HOOK_DIR / "network.js"))
    parts.append(_prepare_response_mapping_source())
    return "\n;\n".join(parts)


# ---------------------------------------------------------------------------
# params.py 생성 (r""" ... """ 안전 처리)
# ---------------------------------------------------------------------------
def _json_for_raw_triple_quotes(obj: Any) -> str:
    """params.py에 넣을 JSON 텍스트.r-triple-quote 리터럴이 깨지지 않도록 처리."""
    text = json.dumps(obj, indent=2, ensure_ascii=False)
    if '"""' in text:
        text = json.dumps(obj, ensure_ascii=False, separators=(",", ":"))
    if '"""' in text:
        # 극히 드문 경우: repr 기반 폴백은 사용자 지정 포맷과 다르므로 이스케이프 분할
        text = json.dumps(obj, ensure_ascii=False).replace('"""', '\\"\\"\\"')
    return text


def write_params_py(
    target: Path,
    network: Any,
    response: Any,
    nexacro: Any,
    header_comment: str = "",
) -> None:
    nj = _json_for_raw_triple_quotes(network if network is not None else [])
    rj = _json_for_raw_triple_quotes(response if response is not None else [])
    xj = _json_for_raw_triple_quotes(nexacro if nexacro is not None else [])

    lines = [
        "# -*- coding: utf-8 -*-",
        f"# Auto-generated by collector.py at {datetime.now(timezone.utc).isoformat()}",
    ]
    if header_comment:
        lines.append(f"# {header_comment}")
    lines.extend(
        [
            "",
            'NETWORK_JSON = r"""',
            nj,
            '"""',
            "",
            'RES_JSON = r"""',
            rj,
            '"""',
            "",
            'NEXACRO_DICT = r"""',
            xj,
            '"""',
            "",
        ]
    )
    target.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# 브라우저에서 데이터 수집
# ---------------------------------------------------------------------------
COLLECT_JS = """
async (opts) => {
    const settleMs = typeof opts === 'object' && opts && Number.isFinite(opts.settleMs)
        ? opts.settleMs
        : 500;
    const runGrid = !!(opts && opts.runGridMapping);

    await new Promise((r) => setTimeout(r, settleMs));

    // getMinifiedNexacroData는 부수효과(콘솔/클립보드) 위주이므로 선택 호출
    let minifiedNote = null;
    try {
        if (typeof window.getMinifiedNexacroData === 'function') {
            minifiedNote = window.getMinifiedNexacroData();
        }
    } catch (e) {
        minifiedNote = String(e);
    }

    let grids = [];
    if (runGrid) {
        try {
            if (typeof window.__mesExtractGridMappings === 'function') {
                const g = window.__mesExtractGridMappings();
                grids = Array.isArray(g) ? g : [];
            }
        } catch (e) {
            grids = [];
        }
    }

    const safeCopy = (v) => {
        try {
            return JSON.parse(JSON.stringify(v));
        } catch (e) {
            return [];
        }
    };

    return {
        network: safeCopy(window.mesApiStore),
        response: grids,
        nexacro: safeCopy(window.nexacroDataStore),
        meta: {
            mesApiStoreLength: Array.isArray(window.mesApiStore) ? window.mesApiStore.length : 0,
            nexacroDataStoreLength: Array.isArray(window.nexacroDataStore) ? window.nexacroDataStore.length : 0,
            getMinifiedNexacroDataResult: minifiedNote,
        },
    };
}
"""


def collect_from_page(
    page,
    *,
    settle_ms: int = 500,
    run_grid_mapping: bool = True,
    post_settle_sleep: float = 0.0,
) -> dict[str, Any]:
    """page.evaluate로 구조화된 스냅샷을 반환한다."""
    if post_settle_sleep > 0:
        time.sleep(post_settle_sleep)
    return page.evaluate(
        COLLECT_JS,
        {"settleMs": int(settle_ms), "runGridMapping": bool(run_grid_mapping)},
    )


def wait_for_mes_api_activity(
    page,
    *,
    min_count: int = 1,
    timeout_ms: float = 120_000,
    poll_ms: int = 400,
) -> bool:
    """
    window.mesApiStore 항목 수가 min_count 이상이 될 때까지 폴링 (선택).
    타임아웃 시 False — 수집은 계속 진행 가능.
    """
    deadline = time.monotonic() + timeout_ms / 1000.0
    while time.monotonic() < deadline:
        try:
            n = page.evaluate(
                "() => Array.isArray(window.mesApiStore) ? window.mesApiStore.length : 0"
            )
            if isinstance(n, int) and n >= min_count:
                return True
        except Exception:
            pass
        page.wait_for_timeout(poll_ms)
    return False


# ---------------------------------------------------------------------------
# 메인 플로우
# ---------------------------------------------------------------------------
def _pause(msg: str) -> None:
    sys.stdout.write(msg)
    sys.stdout.flush()
    try:
        input()
    except EOFError:
        time.sleep(5)
        sys.stderr.write("(stdin closed — waited 5s and continuing)\n")


def run(
    url: str,
    output: Path,
    *,
    headless: bool = False,
    settle_ms: int = 500,
    post_search_sleep: float = 1.0,
    wait_for_api: bool = False,
    api_wait_timeout_ms: float = 120_000,
    url_filter_substring: Optional[str] = None,
    chromium_channel: Optional[str] = None,
    include_nexacro_response: bool = True,
    ext_do_jsonl: Optional[Path] = None,
    ext_do_max_body_chars: int = 500_000,
    post_login_click_selector: Optional[str] = None,
) -> dict[str, Any]:
    from playwright.sync_api import sync_playwright

    bundle = _build_init_script_bundle(
        include_nexacro_response=include_nexacro_response,
    )

    with sync_playwright() as p:
        launch_kw: dict[str, Any] = {"headless": headless}
        if chromium_channel:
            launch_kw["channel"] = chromium_channel

        browser = p.chromium.launch(**launch_kw)
        context = browser.new_context(
            ignore_https_errors=True,
            locale="ko-KR",
        )
        page = context.new_page()

        # 요청/응답 원시 덤프 (옵션 필터) — mesApiStore와 별도로 보관 가능
        captured: list[dict[str, Any]] = []
        ext_do_traffic: list[dict[str, Any]] = []

        def _on_response(resp):
            try:
                u = resp.url or ""
                if url_filter_substring and url_filter_substring not in u:
                    return
                # ext.do 계열만 원하면 기본 필터를 쓸 수 있음
                req = resp.request
                entry = {
                    "url": u,
                    "method": req.method,
                    "status": resp.status,
                }
                # 본문은 대용량일 수 있어 생략 가능; 필요 시 주석 해제
                # entry["request_post_data"] = req.post_data
                captured.append(entry)
            except Exception:
                pass

        if url_filter_substring:
            page.on("response", _on_response)

        def _on_ext_do_request(request):
            try:
                u = request.url or ""
                if "ext.do" not in u:
                    return
                pd = request.post_data
                if (
                    ext_do_max_body_chars > 0
                    and isinstance(pd, str)
                    and len(pd) > ext_do_max_body_chars
                ):
                    pd = pd[:ext_do_max_body_chars] + "\n...<truncated>..."
                ext_do_traffic.append(
                    {
                        "phase": "request",
                        "url": u,
                        "method": request.method,
                        "postData": pd,
                    }
                )
            except Exception:
                pass

        def _on_ext_do_response(response):
            try:
                u = response.url or ""
                if "ext.do" not in u:
                    return
                body = response.text()
                if (
                    ext_do_max_body_chars > 0
                    and isinstance(body, str)
                    and len(body) > ext_do_max_body_chars
                ):
                    body = body[:ext_do_max_body_chars] + "\n...<truncated>..."
                ext_do_traffic.append(
                    {
                        "phase": "response",
                        "url": u,
                        "status": response.status,
                        "body": body,
                    }
                )
            except Exception:
                pass

        if ext_do_jsonl is not None:
            page.on("request", _on_ext_do_request)
            page.on("response", _on_ext_do_response)

        page.add_init_script(bundle)
        page.goto(url, wait_until="domcontentloaded")

        _pause(
            "[1/2] 브라우저에서 로그인을 완료한 뒤, 이 터미널에서 Enter를 누르세요…\n"
        )

        if post_login_click_selector:
            try:
                page.locator(post_login_click_selector).first.click(timeout=30_000)
                time.sleep(0.3)
            except Exception as exc:
                sys.stderr.write(f"경고: post-login click 실패 ({exc})\n")

        _pause(
            "[2/2] MES에서 조회/검색 등 API를 발생시킨 뒤, Enter를 눌러 수집을 시작합니다…\n"
        )

        if wait_for_api:
            ok = wait_for_mes_api_activity(
                page, min_count=1, timeout_ms=api_wait_timeout_ms
            )
            if not ok:
                sys.stderr.write(
                    "경고: 지정 시간 내 mesApiStore 증가를 감지하지 못했습니다. 그대로 스냅샷합니다.\n"
                )

        if post_search_sleep > 0:
            time.sleep(post_search_sleep)

        data = collect_from_page(
            page,
            settle_ms=settle_ms,
            run_grid_mapping=True,
            post_settle_sleep=0,
        )

        if url_filter_substring:
            data["captured_responses_meta"] = captured

        if ext_do_jsonl is not None:
            data["ext_do_traffic_count"] = len(ext_do_traffic)
            ext_do_jsonl.parent.mkdir(parents=True, exist_ok=True)
            with ext_do_jsonl.open("w", encoding="utf-8") as fh:
                for row in ext_do_traffic:
                    fh.write(json.dumps(row, ensure_ascii=False) + "\n")

        write_params_py(
            output,
            data.get("network"),
            data.get("response"),
            data.get("nexacro"),
            header_comment=f"source_url={url}",
        )

        browser.close()
        return data


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Playwright로 Nexacro MES 후킹 데이터를 수집하고 params.py를 생성합니다.",
        epilog="최초 1회: pip install -r requirements.txt 후  playwright install chromium",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--url",
        default=os.environ.get("MES_URL", "").strip(),
        help="MES 웹 URL (미지정 시 MES_URL 환경 변수 또는 대화형 입력)",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=ROOT / "params.py",
        help="생성할 params.py 경로",
    )
    p.add_argument("--headless", action="store_true", help="헤드리스 실행 (기본: 창 표시)")
    p.add_argument(
        "--settle-ms",
        type=int,
        default=500,
        help="evaluate 전 넥사크로 비동기 후킹(setTimeout 100ms 등) 안정화 대기",
    )
    p.add_argument(
        "--post-search-sleep",
        type=float,
        default=1.0,
        help="Enter 이후 추가 대기(초)",
    )
    p.add_argument(
        "--wait-for-api",
        action="store_true",
        help="mesApiStore에 항목이 생길 때까지 최대 --api-wait-timeout-ms 대기",
    )
    p.add_argument(
        "--api-wait-timeout-ms",
        type=float,
        default=120_000,
        help="--wait-for-api 타임아웃(ms)",
    )
    p.add_argument(
        "--log-response-url-substring",
        default="",
        help="지정 문자열이 URL에 포함될 때만 response 이벤트 메타를 captured_responses_meta에 누적",
    )
    p.add_argument(
        "--chromium-channel",
        default="",
        help="예: chrome, msedge (설치된 브라우저 채널)",
    )
    p.add_argument(
        "--no-nexacro-response",
        action="store_true",
        help="nexacro_response.js 미주입 (nexacroDataStore/getMinifiedNexacroData 없음)",
    )
    p.add_argument(
        "--ext-do-jsonl",
        type=Path,
        default=None,
        help="ext.do 요청/응답 본문을 JSONL로 기록할 경로 (미지정 시 기록 안 함)",
    )
    p.add_argument(
        "--ext-do-max-body-chars",
        type=int,
        default=500_000,
        help="ext.do 요청/응답 본문 최대 길이 (0이면 잘라내지 않음)",
    )
    p.add_argument(
        "--post-login-click",
        default="",
        help="첫 Enter 이후 클릭할 CSS 셀렉터 (예: 메뉴 진입 버튼). 선택.",
    )
    return p.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    url = args.url
    if not url:
        try:
            url = input("MES URL을 입력하세요: ").strip()
        except EOFError:
            sys.stderr.write("오류: --url 또는 MES_URL 환경 변수가 필요합니다.\n")
            return 2
    if not url:
        sys.stderr.write("오류: URL이 비어 있습니다.\n")
        return 2

    filt = args.log_response_url_substring.strip() or None
    channel = args.chromium_channel.strip() or None
    click_sel = args.post_login_click.strip() or None

    try:
        data = run(
            url,
            args.output,
            headless=args.headless,
            settle_ms=args.settle_ms,
            post_search_sleep=args.post_search_sleep,
            wait_for_api=args.wait_for_api,
            api_wait_timeout_ms=args.api_wait_timeout_ms,
            url_filter_substring=filt,
            chromium_channel=channel,
            include_nexacro_response=not args.no_nexacro_response,
            ext_do_jsonl=args.ext_do_jsonl,
            ext_do_max_body_chars=args.ext_do_max_body_chars,
            post_login_click_selector=click_sel,
        )
    except Exception as e:
        sys.stderr.write(f"실행 실패: {e}\n")
        return 1

    meta = data.get("meta") or {}
    sys.stdout.write(
        json.dumps(
            {
                "written": str(args.output.resolve()),
                "mesApiStoreLength": meta.get("mesApiStoreLength"),
                "nexacroDataStoreLength": meta.get("nexacroDataStoreLength"),
                "responseGridMappings": len(data.get("response") or []),
                "ext_do_traffic_count": data.get("ext_do_traffic_count"),
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    return 0


# ---------------------------------------------------------------------------
# 선택 개선 예시 (수동 셀렉터 없이 자동 조회에 가깝게 쓰려면):
#   page.get_by_role("button", name=re.compile("조회|검색", re.I)).click()
# 특정 화면 전용이므로 기본 플로우에는 넣지 않음. --post-login-click 으로 대체.
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    raise SystemExit(main())
